import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { of } from 'rxjs';

/**
 * Fonts list.
 */
const FONTS_LIST = [
  'HeliosCond',
  'Marker Felt',
  'Wes',
  '.Helvetica NeueUI',
  'aMavickFont',
  'BigNoodleTitlingCyr',
  'Gobold CYR-LAT',
  'Chuck',
  'Phenomena Black',
  'Star Dust',
  'Brandbe Medium',
  'Coca-Cola Regular rus-lat',
  'soviet font',
  'Chocolate cyr-lat',
  'Munchkin',
  'Buccaneer Cyr',
  'Old Comedy',
  'Redis TYGRA',
  'Astro cyr-lat',
  'Eskal Font4You',
  'Madera TYGRA',
  'LirussTYGRA',
  'Planet N 2 cyr-lat',
  'Drina',
  'Arciform',
  'Gilroy Light',
  'Gotham Pro',
  'Glasten',
  'Gotham Pro Light',
  'Monplesir script',
  '10.12 4 cyr-lat',
  'Marsh Stencil Regular CYR-LAT',
  'PF DinDisplay Pro Black',
  'Amsdam cyr-lat',
  'AO TYPE cyr-lat',
  'Alien Lines cyr-lat',
  'Deadaluss',
  'Plainot',
  'Elixia cyr-lat',
  'Komi',
  'Eveagita Luxury cyr-lat',
  'DublonC',
  'Lay s',
  'Prospect',
  'Column Simple cyr-lat',
  'Marguerite cyr-lat',
  'Geometria',
  'Muller Black',
  'Muller Bold',
  'Iorek Byrnison cyr-lat',
  'Chasing Embers One',
  'YanusC',
  'Muller ExtraBold Italic',
  'Muller Thin',
  'Muller Thin Italic',
  'Romeo RUS-LAT',
  'v_CCAdamKubert',
  'Morning Glory and Cyrillic',
  'Bedrock Kazakh.kz',
  'BigNoodleTooOblique',
  'Batman Forever Alternate Cyr',
  'Enchanted Land cyr-lat',
  'PH 100 Cond Caps',
  'Ribbon Heart',
  'VAL Stencil cyr-lat',
  'Russia Black',
  'Country Western',
  'Phantom cyr-lat',
  'Albertus Medium',
  'Albertus Extra Bold',
  'KZ Times New Roman',
  'Evolventa',
  'Salamander Script',
  'Bough',
  'Ghost Clan Gradient cyr-lat',
  'Kurale',
  'Geometria LF Heavy',
  'Elizabeth_tt Uni',
  'Akademie Alte',
  'Slavianskiy',
  'Pirou Cyrillic',
  'Segoe UI Light',
  'Segoe UI',
  'Segoe UI Semilight',
  'Segoe UI Black',
  'Segoe UI Semibold',
  'Astakhov Skin',
  'Slot Cyrillic',
  'Zetta Papyrus',
  'DINPro-Regular',
  'DINPro-Medium',
  'DINPro-Light',
  'Orbitron',
  'Regina Kursiv',
  'Astakhov Dished',
  'Astakhov First One Stripe',
  'Citrica Cyrillic',
  'Serebro',
  'Bukyvede',
  'Werfus',
  'PF Handbook Pro Thin',
  'A&S Porkchop Primitive Cyrillic',
  'Captcha Code',
  'Ice kingdom (Frozen) Cyrillic',
  'Department H Cyrillic',
  'Elevate PERSONAL USE ONLY',
  'Copperplate Cyrillic',
  'Albertus Med',
  '10467',
  'пиксели просто',
  'CTC Splash Rounded',
  'MVideo',
  'Product Sansi',
  'DejaVu Sans',
  'DejaVu Sans Condensed',
  'Play',
  'Nickainley Normal',
  'StudioScriptC',
  'Katherine Plus',
  'Gang of Three',
  'ILK Comic',
  'DIN Pro Bold',
  'PF Square Sans Pro Medium',
  'PF Square Sans Pro',
  'PF Square Sans Pro Light',
  'PF Square Sans Pro Thin',
  'PF Square Sans Pro Extra Black',
  'Code Pro Light',
  'Code Pro Bold',
  'Code Pro Black',
  'AA Futured',
  'Maya',
  'Supernatural Knight KG',
  'TriodPostnaja',
  'Lato',
  'Lato Light',
  'StylusImperialCyr',
  'SFNS Display',
  'Overpass',
  'Student AWX',
  'Accuratist',
  'PostScriptum',
  'Freeride',
  'Ruler Modern',
  'Double Whiskey AWX',
  'TonkyCaps AWX',
  'Five',
  'Matias',
  'Bemount',
  'Highliner',
  'Shihan',
  'Ikra Slab',
  'Yarin Bold',
  'Yarin',
  'Sensei Medium',
  'Wideface AWX',
  'Prostoy AWX',
  'Heffer',
  'Karmina Bold',
  'PF DinText Pro',
  'Rotonda Bold',
  'Roboto Slab',
  'P22 Underground CY Pro',
  'Mart AWX',
  'KZ Arial',
  'v_KomikaAxis',
  'kurbanistika',
  'Kazmann Sans',
  'GOST_type_A',
  'Demian Sakha',
  'FreeSans',
  'COLORADO X',
  'Smeshariki Font',
  'Exo 2.0',
  'Exo 2.0 Black',
  'Exo 2.0 Extra Bold',
  'Exo 2.0 Extra Light',
  'Exo 2.0 Light',
  'Exo 2.0 Medium',
  'URW Gothic L',
  'Kramola',
  'Snowstorm Black',
  'Snowstorm Bold',
  'Snowstorm Inline',
  'Snowstorm Kraft',
  'Snowstorm Light',
  'Snowstorm',
  'TT Prosto Sans Condensed DEMO',
  'Mytupi',
  'OldSansBlack',
  'Chadwick Cyrillic',
  'Big Orange Cyrillic',
  'Teletoon Cyrillic',
  'E4 Digital Cyrillic',
  'MaximaEFCyr-Medium',
  'HussarBoldOriginal',
  'Tabarra Black',
  'VW Headline OT-Black',
  'Slot SSi RUS',
  'FunZone Two',
  'The Huntsman',
  'Retrospective 3 Cyrillic',
  'VAG World',
  'NK767 Alt',
  'GTAPricedown Bl',
  'Gagalin',
  'Old Rosa',
  'Realize My Passion',
  'v_CCZoinks',
  'Amphi CYR',
  'VipnagorgiallaCyrillized',
  'Roddenberry CYRILLIC',
  'CgFiorello_Cyrillic',
  'Pixel Digivolve Cyrillic',
  'Cyberfall_Cyrillic',
  'AA American Captain',
  'AA BadaBoom BB',
  'AA Clobberin Time Smooth',
  'Russo One',
  'Oranienbaum',
  'Pravda Newspaper CYR-ENG',
  'Forum',
  'FiveMinutes',
  'Eurotype 2016',
  'Alabama',
  'Arno Pro Caption',
  'Palatino Linotype',
  'Times New Roman',
  'Arial',
  'Tahoma',
  'Open Sans',
  'Roboto',
];

/**
 * Fonts service.
 */
@Injectable()
export class FontsService {
  /**
   * Get fonts families.
   */
  public getFamilies(): Observable<string[]> {
    const distinctFonts = new Set(FONTS_LIST);
    return of(Array.from(distinctFonts.values()));
  }
}
